server:
  port: 8001

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account
  #微服务名字
  application:
    name: account

eureka:
  client: #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7000.com:7000/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true #访问路径显示IP地址
    instance-id: kncloud-account-8001 #注册进eureka服务名称信息

#开启hystrix功能
feign:
  hystrix:
    enabled: true

info:
  app.name: com.kn.cloud
  company.name: www.kn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
